function datiexoscheletro1 = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  DATIEXOSCHELETRO1 = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  DATIEXOSCHELETRO1 = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  datiexoscheletro1 = importfile("/Users/simonesgorbati/Desktop/complete_control/dati_exoscheletro_2024-12-05_00-05-29_719.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 05-Dec-2024 00:29:56

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 9);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Timestamp", "PosIsDeg", "ForceIs", "AccX", "AccY", "AccZ", "GyroX", "GyroY", "GyroZ"];
opts.VariableTypes = ["datetime", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Timestamp", "InputFormat", "yyyy-MM-dd HH:mm:ss.SSS");

% Import the data
datiexoscheletro1 = readtable(filename, opts);

end
